name: Create and Show Tags of ECS By KooCLI
on:
  push:
    branches:
        master
jobs:
  Create-Show-Tags:
    runs-on: macos-latest
    steps:
      - name: Authenticate to Huawei Cloud
        uses: huaweicloud/auth-action@v1.0.0
        with: 
          access_key_id: ${{ secrets.ACCESSKEY }} 
          secret_access_key: ${{ secrets.SECRETACCESSKEY }}
          region: '<region>'

      - name: Create and Show Tags of ECS by KooCLI
        uses: huaweicloud/huaweicloud-cli-action@v1.0.0
        with:
          command_list: |
            hcloud ECS BatchCreateServerTags --cli-region="cn-north-4" --project_id="0*******************b" --server_id="123" --action="create" --tags.1.value="value" --tags.1.key="key"
            hcloud ECS ShowServerTags --cli-region="cn-north-4" --project_id="0*******************b" --server_id="123"