name: Create and Show Tags of ECS By KooCLI By KooCLI
on:
  push:
    branches:
        master
jobs:
  Create-Show-Tags:
    runs-on: ubuntu-latest
    steps:
      - name: Create and Show Tags
        uses: huaweicloud/huaweicloud-cli-action@v1.0.0
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: 'cn-north-4'
          commandList: |
            hcloud ECS BatchCreateServerTags --cli-region="cn-east-3" --project_id="0*******************b" --server_id="123" --action="create" --tags.1.value="value" --tags.1.key="key"
            hcloud ECS ShowServerTags --cli-region="cn-east-3" --project_id="0*******************b" --server_id="123"