name: List Versions of ECS With Default Region By KooCLI
on:
  push:
    branches:
        master
jobs:
  Setup-KooCLI-And-Run-Codecheck:
    runs-on: ubuntu-latest
    steps:
   
      - name: Setup KooCLI
        uses: huaweicloud/huaweicloud-cli-action@v1.0.0
        with:
          access_key: ${{ secrets.ACCESSKEY }}
          secret_key: ${{ secrets.SECRETACCESSKEY }}
          region: 'cn-north-4'
          
      - name: Run CodeCheck Task
        run: |
          hcloud CodeCheck CreateTask --cli-region="cn-north-4" --project_id="your_project_id" --rule_sets.1.language="rule_language" --git_branch="your_branch" --language.1="your_language" --git_url="your_repository_url"
          hcloud CodeCheck RunTask --cli-region="cn-north-4" --task_id="your_codecheck_task_id"
          hcloud CodeCheck ShowTaskDetail --cli-region="cn-north-4" --task_id="your_codecheck_task_id"